apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.podName }}
  labels:
    app.kubernetes.io/app: {{ .Values.podName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.podName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.podName }}
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresDb }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresUser }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: {{ .Values.mountName }}
              mountPath: {{ .Values.mountPath }}
          args: ["-p", {{ .Values.containerPort | quote }}]
      volumes:
        - name: {{ .Values.mountName }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvcName }}
